server.modules = (
    "mod_access",
    "mod_alias",
    "mod_setenv",
    "mod_cgi",
    "mod_accesslog"
)

server.document-root = "/www/pages/"
server.errorlog = "/var/log/lighttpd.error.log"
accesslog.filename = "/var/log/lighttpd.access.log"

index-file.names = ( "index.html" )

mimetype.assign = (
    ".html" => "text/html",
    ".htm"  => "text/html",
    ".txt"  => "text/plain",
    ".css"  => "text/css",
    ".js"   => "text/javascript",
    ".json" => "application/json"
)

url.access-deny = ( "~", ".inc" )
static-file.exclude-extensions = ( ".php", ".pl", ".fcgi", ".cgi" )

$HTTP["url"] =~ "^/cgi-bin/" {
    cgi.assign = (
        ".cgi" => "/usr/bin/perl",
        ".pl"  => "/usr/bin/perl"
    )
}
