# Yocto build container (glibc >= 2.38)
FROM ubuntu:24.04

USER root
ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && apt install -y \
    gawk wget git-core diffstat zip unzip texinfo \
    gcc-multilib build-essential chrpath socat file cpio python3 \
    python3-pip python3-pexpect xz-utils debianutils debconf-utils iputils-ping \
    libsdl1.2-dev xterm tar locales net-tools rsync sudo vim curl zstd \
    liblz4-tool libssl-dev bc lzop libgnutls28-dev efitools git-lfs \
    gdb xxd tmux libncurses-dev && \
    rm -rf /var/lib/apt/lists/*

RUN pip3 install numpy websockets

RUN locale-gen en_US.UTF-8 && \
    update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LC_ALL en_US.UTF-8

# Yocto needs 'source' command for setting up the build environment
RUN rm /bin/sh && ln -s bash /bin/sh

ARG USER
ARG host_uid
ARG host_gid
RUN echo "${USER} ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/${USER} && \
    chmod 0440 /etc/sudoers.d/${USER} && \
    groupadd -f -g $host_gid $USER && \
    useradd -g $host_gid -m -s /bin/bash -u $host_uid $USER

USER $USER
