# Generated by iptables-save v1.8.10 on Tue Nov  4 21:41:41 2025
*filter
:INPUT ACCEPT [225127:197805449]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [140289:76048622]
-A INPUT -p tcp -m tcp --dport 22 -j DROP
-A INPUT -i lo -p tcp -m tcp --dport 1236 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 1236 -j DROP
COMMIT
# Completed on Tue Nov  4 21:41:41 2025