[Unit]
Requires=bluealsa.service
After=bluealsa.service bluetooth.service
PartOf=bluetooth.service

[Service]
ExecStart=
ExecStart=/usr/bin/bluealsa-aplay --pcm=bt_audio --pcm-buffer-time=1000000 --pcm-period-time=250000
Restart=always
RestartSec=2
